### ISSUE TITLE
AutoGrowTextInput inside ScrollView

### ISSUE THREAD

**Issue by VictorVarghese** [wix/react-native-autogrow-textinput#16]
```
<ScrollView>
<<AutoGrowTextInput/>
<View/>
<View>
</ScrollView>
```

In this setup the TextInput scrolls seperately when the textinput is focused(or when keyboard is open)
The expected result would parent scrollview working.
But textinput has a seperate scroll.
Anyway to fix this issue?
Thanks in advance.

PS: scrolling works proper if the textinput is not in focus.

**Comment by artald** [comment]
This behavior is not specific for this package.

`AutoGrowTextInput` is just a multi-line `TextInput`. Multi-line `TextInput` has an inner scroll container. 

Using a ScrollView within a ScrollView is a problematic layout when they are both scrolling in the same direction.

One possible solution would be to let the`AutoGrowTextInput` extend its height indefinitely by setting the `maxHeight` prop to a really large number. I think that this way it won't have an inner scroll because then it will take the actual height and make the scroll content larger as well.
Another option could be to disable scrolling when necessary.

**Comment by VictorVarghese** [comment]
Maanged to disable the scroll by commenting the android specific code in onContentChange()
Now scroll is disabled in textinput and works properly .Thanks for the awseome lib.
 ```
_onContentSizeChange(event) {
   /*  if(ANDROID_PLATFORM) {
      if(!this.state.androidFirstContentSizeChange) {
        return;
      }
      this.setState({androidFirstContentSizeChange: false});
    } */
    this._handleNativeEvent(event.nativeEvent);

    if (this.props.onContentSizeChange) {
      this.props.onContentSizeChange(event);
    }
  }
```

**Comment by artald** [comment]
@VictorVarghese thanks!

This code is there to fix a very specific bug on Android (see the comment above the `_onContentSizeChange` method). It's possible that this was fixed in more advanced RN versions that came after this fix was applied.

That said, I don't see how this help to disable scrolling. what's the idea here?
