### ISSUE TITLE
JSON value 'auto' of type NSString cannot be converted

### ISSUE THREAD

**Issue by pdavid0** [wix/react-native-autogrow-textinput#20]
![simulator screen shot jun 21 2017 5 38 49 pm](https://user-images.githubusercontent.com/1034292/27407977-930c8d72-56a8-11e7-8d5a-c378388e6b98.png)

```
import {AutoGrowingTextInput} from "react-native-autogrow-textinput";

<AutoGrowingTextInput
            style={styles.textInput}
            placeholder={I18n.t("chatRoom.typeMessage")}
            placeholderTextColor="#868B97" //$paletteGrey2
            underlineColorAndroid='rgba(0,0,0,0)'
            enablesReturnKeyAutomatically={true}
            value={this.state.text}
            onChangeText={text => this.setState({text})}
            blurOnSubmit={false}
            returnKeyType='send'
            onSubmitEditing={this.sendMessage}
          />
```
style
```
textInput:           {
    alignSelf:       "center",
    height:          30,
    width:           100,
    backgroundColor: "$white",
    color:           "$colorTextDark",
    flex:            1,
    padding:         0,
    margin:          0,
    fontSize:        15,
  },
```
R : 0.41.2
RN : 15.5.4

**Comment by andyzanli** [comment]
I encountered the same issue. The problem is that the height style property of `_renderTextInputIOS()
` in the file `node_modules/react-native-autogrow-textinput/src/AutoGrowingTextInput.js` is set to 'auto'.

It seems strange that a style property of `{ height: 'auto' }` would be included in the script when it appears to be causing this problem. The way to prevent this error is to change the property of the height to `{ height: this.props.initialHeight }` and set the height accordingly as props in `<AutoGrowingTextInput ... initialHeight: {100} />`

**Comment by artald** [comment]
Hey guys,

We updated the component to work with the latest versions of RN which supports auto growing multi line inputs out of the box - unfortunately, this is only the case for iOS.

This was a major version (4) for this package, for older RN versions you can use the previous version (3).

**Comment by GioLogist** [comment]
Is there a downfall to simply removing the following in the repo itself? 
`, {height: 'auto'}`

I've had to repeat this step whenever I clean my node_modules, as I am not yet able to upgrade RN on that specific build.

**Comment by artald** [comment]
@GioLogist as i've mentioned in the previous comment, in case you're using an older version of RN, you can use version 3 of this package (i.e. specify `"react-native-autogrow-textinput": "^3.0.0"` in your `package.json`).

**Comment by GioLogist** [comment]
@artald ADD + ignorance on my behalf lead me to not read the entire message - hah, thanks! ✊
