### ISSUE TITLE
5.0.0 is not working on android - height is not changing.

### ISSUE THREAD

**Issue by EyalSi** [wix/react-native-autogrow-textinput#44]
Seems like when using version 5.0.0 in Android the height is not changed when needed. In previous versions, I was using the fix at https://github.com/wix/react-native-autogrow-textinput/issues/28, but now, the method _handleNativeEvent doesn't exist. 
This is so weird, the purpose of this lib is to grow automatically, and that's not working...
10x,
EyalS

**Comment by artald** [comment]
which RN version are you using?

**Comment by EyalSi** [comment]
Thanks for looking at this.
I'm using RN 0.52.0.

**Comment by artald** [comment]
As i've mentioned in the other issue, auto-grow is now available out of the box in regular RN text-inputs. so _handleNativeEvent is no longer necessary, we're not setting the height ourselves anymore.

The reason we still keep using this component in modern RN versions is because of very specific native fixes that we added, which I don't know if you're even using or plan to use.

I checked the example project and it auto-grows as expected on both Android and iOS, so I don't know why it is not working for you.

Maybe some styles you applied are causing issues? Have you tried running the example project?

**Comment by EyalSi** [comment]
Hi Artald, 
I've tried already removing all styles but had the same problem. Just moved back to the standard text input.
10x,
EyalS

**Comment by Noitidart** [comment]
@artald may you please link us to the note in the react native release section ( https://github.com/facebook/react-native/releases )where it says they autogrow now. I can't find it, i was hoping to look at the related commits to see how they do it.

**Comment by artald** [comment]
Hi @Noitidart 

iOS support added on RN44 [here](https://github.com/facebook/react-native/commit/1b013cd30ce201cafb376782bdf427f601940220) and [here](https://github.com/facebook/react-native/commit/26e2c08544f3beac9926652f1b8f38ca7647df6e). Android support was added on RN50 [here](https://github.com/facebook/react-native/commit/c550f27a4e82402b966567d7b79a8b1f1d1491a5)

**Comment by Noitidart** [comment]
Thank you sir very much especially for even linking me to it!!
